DROP DATABASE IF EXISTS defaultCharacterdb;
CREATE DATABASE defaultCharacterdb;

DROP DATABASE IF EXISTS itemsdb;
CREATE DATABASE itemsdb;

DROP DATABASE IF EXISTS iddb;
CREATE DATABASE iddb;

DROP DATABASE IF EXISTS activeObjectsdb;
CREATE DATABASE activeObjectsdb;

DROP DATABASE IF EXISTS playersdb;
create DATABASE playersdb;